<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;

class PredictiveModel extends Model
{
    use HasFactory;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'company_id',
        'machine_id',
        'model_type',
        'status',
        'accuracy_score',
        'confidence_threshold',
        'features',
        'hyperparameters',
        'last_trained_at',
        'last_prediction_at',
        'training_samples',
        'notes',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'accuracy_score' => 'decimal:2',
        'confidence_threshold' => 'decimal:2',
        'features' => 'array',
        'hyperparameters' => 'array',
        'last_trained_at' => 'datetime',
        'last_prediction_at' => 'datetime',
        'training_samples' => 'integer',
    ];

    /**
     * Get the company that owns the predictive model.
     */
    public function company(): BelongsTo
    {
        return $this->belongsTo(Company::class);
    }

    /**
     * Get the machine that this model predicts for.
     */
    public function machine(): BelongsTo
    {
        return $this->belongsTo(Machine::class);
    }

    /**
     * Get the predictions generated by this model.
     */
    public function predictions(): HasMany
    {
        return $this->hasMany(FailurePrediction::class);
    }

    /**
     * Check if the model is active and ready for predictions.
     */
    public function isActive(): bool
    {
        return $this->status === 'active';
    }

    /**
     * Check if the model needs retraining (e.g., hasn't been trained in 30 days).
     */
    public function needsRetraining(int $daysThreshold = 30): bool
    {
        if (!$this->last_trained_at) {
            return true;
        }

        return $this->last_trained_at->diffInDays(now()) >= $daysThreshold;
    }

    /**
     * Get active predictions for this model.
     */
    public function activePredictions(): HasMany
    {
        return $this->predictions()->where('status', 'active');
    }

    /**
     * Scope to get only active models.
     */
    public function scopeActive($query)
    {
        return $query->where('status', 'active');
    }

    /**
     * Scope to get models by type.
     */
    public function scopeOfType($query, string $type)
    {
        return $query->where('model_type', $type);
    }
}
